import { describe, expect, it } from "vitest";
import {
  MAX_TOTAL_ATTEMPTS,
  CHILD_BIND_TIMEOUT_MS,
  FIRST_ACTIVITY_TIMEOUT_MS,
  INACTIVITY_TIMEOUT_MS,
  TOOL_EXECUTION_TIMEOUT_MS,
  ATTEMPT_HARD_TIMEOUT_MS,
  SESSION_CREATE_TIMEOUT_MS,
  SESSION_ABORT_TIMEOUT_MS,
  ORIGINAL_SETTLEMENT_TIMEOUT_MS,
  PARENT_ABORT_SETTLEMENT_TIMEOUT_MS,
  RECOVERY_ENQUEUE_TIMEOUT_MS,
  MAX_UNKNOWN_INTERNAL_RETRIES,
  MAX_UNKNOWN_RETRY_DELAY_MS,
  MAX_UNKNOWN_RETRY_TOTAL_MS,
  DEFAULT_RATE_LIMIT_TTL_MS,
  MIN_RATE_LIMIT_TTL_MS,
  MAX_RATE_LIMIT_TTL_MS,
  PARENT_RECOVERY_MAX_RESULT_CHARS,
  COMPLETED_TASK_TOMBSTONE_MS,
  INTERNAL_SESSION_TOMBSTONE_MS,
  MAX_ACTIVE_TASKS,
  MAX_TOMBSTONES,
} from "../src/recovery-policy.js";

describe("recovery policy constants", () => {
  it("defines the exact design and amendment values", () => {
    expect(MAX_TOTAL_ATTEMPTS).toBe(3);
    expect(CHILD_BIND_TIMEOUT_MS).toBe(15000);
    expect(FIRST_ACTIVITY_TIMEOUT_MS).toBe(60000);
    expect(INACTIVITY_TIMEOUT_MS).toBe(180000);
    expect(TOOL_EXECUTION_TIMEOUT_MS).toBe(600000);
    expect(ATTEMPT_HARD_TIMEOUT_MS).toBe(1800000);
    expect(SESSION_CREATE_TIMEOUT_MS).toBe(15000);
    expect(SESSION_ABORT_TIMEOUT_MS).toBe(10000);
    expect(ORIGINAL_SETTLEMENT_TIMEOUT_MS).toBe(15000);
    expect(PARENT_ABORT_SETTLEMENT_TIMEOUT_MS).toBe(15000);
    expect(RECOVERY_ENQUEUE_TIMEOUT_MS).toBe(10000);
    expect(MAX_UNKNOWN_INTERNAL_RETRIES).toBe(1);
    expect(MAX_UNKNOWN_RETRY_DELAY_MS).toBe(10000);
    expect(MAX_UNKNOWN_RETRY_TOTAL_MS).toBe(15000);
    expect(DEFAULT_RATE_LIMIT_TTL_MS).toBe(600000); // P-02
    expect(MIN_RATE_LIMIT_TTL_MS).toBe(1000); // P-04
    expect(MAX_RATE_LIMIT_TTL_MS).toBe(86400000); // P-04
    expect(PARENT_RECOVERY_MAX_RESULT_CHARS).toBe(32000); // P-07
    expect(COMPLETED_TASK_TOMBSTONE_MS).toBe(300000);
    expect(INTERNAL_SESSION_TOMBSTONE_MS).toBe(300000);
    expect(MAX_ACTIVE_TASKS).toBe(1000);
    expect(MAX_TOMBSTONES).toBe(2000);
  });
});
